ttvnp/ttj-asset-android-client

.circleci/config.yml, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileUploadDocumentIDFragment.kt, app/src/main/res/values/strings.xml, fastlane/Fastfile, release_notes.txt
=> (WIP) Fix bugs for KYC

app/src/main/res/values-ja/strings.xml
improve japanese text for notification.
=> [improve/Android] Change Japanese text for notification for sending points/coins

app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml
=> [improvement] Language settings is not user friendly

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/BaseActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/SettingsChangePasswordActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSettingsFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/MainSettingsPresenterImpl.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SettingsChangePasswordPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/target/MainSettingsPresenterTarget.kt, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/driver/SharedPreferencesDriver.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/DeviceRepositoryImpl.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/service/DeviceService.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/service/response/DeviceServiceResponse.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/store/DeviceDataStore.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/store/DeviceInfoDataStore.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/model/LogoutModel.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/repository/DeviceRepository.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/use_case/DeviceUseCase.kt
- add logout function and remove db and share preference after logout.
- move dismiss and show progress dialog to presenter.
=> [Android] Logout

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileUploadDocumentIDFragment.kt
change condition for validation under review
=> [improve/Android] Add validation should not be able to send ID document unless it inputs all the profile

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SettingsChangePasswordPresenter.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/model/UserModel.kt
update return wrong condition.
=> [desktop] Change password

app/src/main/res/layout/activity_settings_change_password.xml, app/src/main/res/layout/fragment_tutorial_code.xml
allow password input more than 10 characters.
=> [improve/Android] Can input only 10 characters and numbers for password for login

build.gradle, release_notes.txt
- Add change password
- Add logout
- Add require password to send assets
=> Version up to 19 (1.0.15)

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/BaseActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/LaunchActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/TutorialActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/error/ErrorMessageGenerator.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/BaseFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSettingsFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/MainSettingsPresenterImpl.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/driver/SharedPreferencesDriver.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/DeviceRepositoryImpl.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/store/DeviceInfoDataStore.kt
Handle logout without removing app language
Handle logout error
Handle check message is not yet translated
=> [improve/android] check message is not yet translated

app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml
=> [new feature/Android]  Send to any Stellar Account

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/SendActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/TutorialActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSendFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountFormByStellarFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SendAmountFormByStellarPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/target/SendAmountFormByStellarPresenterTarget.kt, app/src/main/res/layout/fragment_main_send.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
update sending stellar without scanning QR.
=> Send to any stellar account

app/build.gradle, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainHomeFragment.kt, app/src/main/res/layout/fragment_main_home.xml, build.gradle, data/build.gradle, data/src/main/res/values/strings.xml, dependencies.gradle, domain/build.gradle, domain/src/main/res/values/strings.xml, gradle/wrapper/gradle-wrapper.properties
- fixed compile is obsolete and has been replaced with implementation…
- add progress bar for home page.
=> Fix compile is obsolete and has been replaced with implementation and api

app/src/local/AndroidManifest.xml, app/src/main/AndroidManifest.xml, dependencies.gradle
=> Fix build error and warning

data/build.gradle
- add :
- buildConfigField "String", "HORIZON_URL"
- buildConfigField "String", "ISSUER_ACCOUNT_ID"
=> Fix build error

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountFormByStellarFragment.kt, app/src/main/res/layout/fragment_send_amount_form.xml, app/src/main/res/layout/fragment_send_amount_form_by_stellar.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
=> [improve/Android] Change Jp text

data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/entity/StellarAccountEntity.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/entity/UserTransactionEntity.kt
- update default value for new field of DB.
=> [bug/Android] When updating new version, it shows errors or downs the app

data/build.gradle, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/UserRepositoryImpl.kt
=> Local check

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/LaunchActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/BaseFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainHomeFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainReceiveFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSendFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileEditFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/MainReceivePresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/MainSendPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/target/MainReceivePresenterTarget.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/target/MainSendPresenterTarget.kt, app/src/main/res/layout/fragment_main_receive.xml, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/UserRepositoryImpl.kt, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/UserTransactionRepositoryImpl.kt
- prevent many requests to server side.
=> [bug/Android] Shows an error when launching app

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/LaunchActivity.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/adapter/PaymentHistoryViewAdapter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainHomeFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/LaunchPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/MainHomePresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/view/PaymentHistoryViewHolder.kt, app/src/main/res/layout/view_footer_loading.xml, build.gradle, data/src/main/kotlin/com/ttvnp/ttj_asset_android_client/data/repository/DeviceRepositoryImpl.kt, gradle/wrapper/gradle-wrapper.properties
- check dispose for Start Screen.
- set delay when scroll down to prevent from too many requests.
=> Bug android shows error to scroll down in top

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/activity/SendActivity.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/model/QRCodeInfoModel.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/model/QRCodeInfoStellarInfoModel.kt, domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/model/QRCodeType.kt
- change enum value type to string type.
=> [Crashlytics/Android] #54 SendActivity

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/BaseFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountFormByStellarFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountFormFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendEmailFormFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SendAmountFormByStellarPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SendEmailFormPresenter.kt
- make sure that it will show network error when network isn't available.
=> [improve/Android] Show network error message

app/build.gradle, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountConfirmFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountFormByStellarFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SendAmountFormByStellarPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/target/SendAmountFormByStellarPresenterTarget.kt, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml, data/build.gradle
- update validation for stellar.
=> [update/Android] Validate to send by stellar address

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSendFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainSettingsFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SendAmountConfirmFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SendAmountConfirmPresenter.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/presenter/SettingsSecurityPresenter.kt
- prevent crash from calling presenter.
=> [bug/Android] Crash app when changing languages after transaction

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileUploadDocumentIDFragment.kt, build.gradle
update com.android.tools.build:gradle:3.3.0 to com.android.tools.build:gradle:3.3.1
=> Fix production build error.

app/src/main/res/values-ja/strings.xml, app/src/main/res/values-vi/strings.xml, app/src/main/res/values/strings.xml
- update string for snc address.
=> [improve/Android] Change text to check SNC address

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/MainHomeFragment.kt
- handle request when token is expired
Asana's Link: https://app.asana.com/0/515943528653251/1120342839055094
=> [Improvement/Android] Handle request to server when token is expired.

domain/src/main/kotlin/com/ttvnp/ttj_asset_android_client/domain/util/EmailValidator.kt
- update email validation.
https://app.asana.com/0/515943528653251/1125671975919948
=> [Improve/android] Validation email

app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/BaseMainFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileEditFragment.kt, app/src/main/kotlin/com/ttvnp/ttj_asset_android_client/presentation/ui/fragment/SettingsProfileUploadDocumentIDFragment.kt
- check result intent when getting image.
=> Loading of uploading an image for KYC doesn't finish
